version: '3.7'
services:
    telegram:
        build: ./TelegramManager/
        environment:
            POSTGRES_DB_HOST: database
            TELEGRAM_API_TOKEN: "$TELEGRAM_API_TOKEN"
            POSTGRES_USER: "$POSTGRES_USER"
            POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
            POSTGRES_DB: "$POSTGRES_DB"
            CREATOR_ID: "$CREATOR_ID"
        restart: always
        links:
            - database
        volumes_from:
            - database
        depends_on:
            - database

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
        
    database:
        restart: always
        image: postgres:13.3
        volumes:
            - db-NSKTEST:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_USER: "$POSTGRES_USER"
            POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
            POSTGRES_DB: "$POSTGRES_DB"
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
        - 5432:5432

    

volumes:
    db-NSKTEST:

     



                    
